### ISSUE TITLE
My graph is not updating and more

### ISSUE THREAD

**Issue by GripenANM** [ArtificialQualia/PyEveLiveDPS#59]
my graph is not updating and the breakdown list is not showing

**Comment by GripenANM** [comment]
originally is working fine, but after i restart my pc and launch it, it stopped working, i can still see the breakdown list, but just cant open it

**Comment by ArtificialQualia** [comment]
Is PELD tracking the right character?  If you've logged in other characters in the past 24 hours, it may be selecting the wrong one.  Check which it is tracking in the 'Character...' dropdown menu, and change it if needed.

It will also be helpful to attach your PELD logs, put `%APPDATA%\PELD` into your File Explorer bar and attach the `PELD.log` file here.

**Comment by GripenANM** [comment]
yes the values are updating just the graph not updating

**Comment by GripenANM** [comment]
btw i cant upload the log file
it said its not supported

**Comment by GripenANM** [comment]
2020-05-13 13:08:29,398:root:ERROR - invalid command name ".114727504.114728528.92222992.95471856"
Traceback (most recent call last):
  File "animate.py", line 125, in animate
  File "labelHandler.py", line 63, in updateLabel
  File "labelHandler.py", line 141, in updateLabel
  File "tkinter\__init__.py", line 1331, in __setitem__
  File "tkinter\__init__.py", line 1324, in configure
  File "tkinter\__init__.py", line 1315, in _configure
_tkinter.TclError: invalid command name ".114727504.114728528.92222992.95471856"
2020-05-13 13:08:29,455:root:ERROR - invalid command name ".114727504.114728528.92222992.95471856"

**Comment by GripenANM** [comment]
an now i got this in the middle of my screen, i think restarting should help though
https://gyazo.com/61aa702004e8db0f9bb26520fc571323

**Comment by ArtificialQualia** [comment]
I don't think the error you shared is the right error, looks like it is just a result of whatever the real root cause is.

You should be able to upload your log file, make sure it is the `PELD.log` file and NOT the `PELD.json` file.  The json file will say it's not supported.

You can always give restarting a go, let me know if that works.  In either case the PELD.log file should be helpful.

**Comment by GripenANM** [comment]
https://gyazo.com/f3f9b633012b00bc539ae5fcfba9489d

**Comment by GripenANM** [comment]
well i cant

**Comment by GripenANM** [comment]
https://i.gyazo.com/fbc900107720f827c698262cfd32b913.png

**Comment by ArtificialQualia** [comment]
Huh, bizarre, that works for me and others I've worked with in the past.  Sorry to be a pain, but can you try zipping that file and attaching the zip file to this issue?  That may work.

**Comment by GripenANM** [comment]
let me try

**Comment by GripenANM** [comment]
[PELD - Copy.zip](https://github.com/ArtificialQualia/PyEveLiveDPS/files/4625603/PELD.-.Copy.zip)

**Comment by ArtificialQualia** [comment]
Thanks for the logs!  Glad that worked.

I've fixed that error that is all over the logs, which was related to how that little square was being left behind in the middle of your screen.  [You can download the fixed version (v2.6.1) here.](https://github.com/ArtificialQualia/PyEveLiveDPS/releases/tag/v2.6.1)

Since that little square was spitting out errors and the size of the log file is limited, we may have lost your original error with regards to your graph not updating, or it could be possibly related to the same issue that is fixed in v2.6.1.  

Before trying the fixed version, make sure you don't have any little squares left behind on your screen by either manually killing the PELD.exe process(es) or restarting your PC, then try v2.6.1 and let me know if you are still having issues.

**Comment by GripenANM** [comment]
still not working
https://gyazo.com/3b5169e44b73c522f052056146b4cfcf

**Comment by GripenANM** [comment]
it working fine now thanks for the help
